# Generated by Django 5.2.8 on 2025-12-03 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wichtel', '0002_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_drawings', to='wichtel.drawing')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_giver', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('drawing', 'giver'), name='unique_giver_per_drawing'), models.UniqueConstraint(fields=('drawing', 'receiver'), name='unique_receiver_per_drawing'), models.CheckConstraint(condition=models.Q(('giver', models.F('receiver')), _negated=True), name='no_self_gifting')],
            },
        ),
    ]
