# Generated by Django 5.2.9 on 2025-12-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wichtel', '0003_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
