# Generated by Django 5.2.9 on 2025-12-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wichtel', '0004_add_code_name_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
